//
// Created by Renatus Madrigal on 3/2/2025.
//

#ifndef MANDELBROTSET_INCLUDE_MANDELBROT_MANDELBROTSET_H
#define MANDELBROTSET_INCLUDE_MANDELBROT_MANDELBROTSET_H

#endif //MANDELBROTSET_INCLUDE_MANDELBROT_MANDELBROTSET_H
