name: LaTeX report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX
        run: |
          make -C doc

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: doc/report.pdf

      - name: Upload report-cn
        uses: actions/upload-artifact@v2
        with:
          name: report-cn
          path: doc/report-cn.pdf

      - name: cleanup
        run: |
          make -C doc clean-all

